core/urls.py
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path("contactus/",views.contactus,name="contactus"),
     path("productlist/",views.productlist,name="productlist"),
   # path('product/<slug>/', views.variations, name='product'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    #path('add-to-cart/<slug>/<int:variation_id>/', add_to_cart, name='add-to-cart'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path("profile/",views.profile,name="profile"),
    path("orders/",views.orders,name="orders")
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 10vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>

{% include "navbar.html" %}

<body>

  <div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
  </div>

  {% block content %}
  {% endblock content %}

  {% block extra_body %}
  {% endblock %}

  {% include "footer.html" %}
  {% include "scripts.html" %}

  {% block extra_scripts %}
  {% endblock extra_scripts %}
</body>

</html>

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<main>
  <div class="container wow fadeIn" style="padding-top: 3cm;">
    <h2 class="my-5 h2 text-center">Checkout form</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body" id="checkout-form">
            {% csrf_token %}

            <h3>Shipping address</h3>

            <div class='hideable_shipping_form'>

              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address'
                  class='form-control' />
                <label for="shipping_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2'
                  class='form-control' />
                <label for="shipping_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.shipping_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>


                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="shipping_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip'
                    class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>

              <div class="col-lg-4 col-md-6 mb-4">
                <label for="mobile_number">Mobile number</label>
                <input type='text' placeholder='Mobile number' id='mobile_number' name='mobile_number'
                  class='form-control' />
                <div class="invalid-feedback">
                  Mobile number required
                </div>
              </div>

              <!-- <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="same_billing_address"
                  id="same_billing_address">
                <label class="custom-control-label" for="same_billing_address">Billing address is the same as my
                  shipping address</label>
              </div>-->
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_shipping"
                  id="set_default_shipping">
                <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
              </div>

            </div>

            <!-- {% if default_shipping_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
              <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{
                default_shipping_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}-->

            <hr>

            <h3>Billing address</h3>

            <div class='hideable_billing_form'>
              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address'
                  class='form-control' />
                <label for="billing_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2'
                  class='form-control' />
                <label for="billing_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.billing_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="billing_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>

              </div>

              <div class="col-lg-4 col-md-6 mb-4">
                <label for="mobile_number">Mobile number</label>
                <input type='text' placeholder='Mobile number' id='mobile_number' name='mobile_number'
                  class='form-control' />
                <div class="invalid-feedback">
                  Mobile number required
                </div>
              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
              </div>

            </div>

            <!-- {% if default_billing_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
              <label class="custom-control-label" for="use_default_billing">Use default billing address: {{
                default_billing_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}-->
            <hr>



            <h3>Payment option</h3>

            <div class="d-block my-3">
              {% for value, name in form.fields.payment_option.choices %}
              {% if value == 'C' %}
              <div class="custom-control custom-radio">
                <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                  class="custom-control-input" required>
                <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
              </div>
              {% endif %}
              {% endfor %}
            </div>

            <hr class="mb-4">
            <button id="place-order-btn" class="btn btn-primary btn-lg btn-block" type="button">Place Order</button>

          </form>

        </div>

      </div>

      <div class="col-md-4 mb-4">
        {% include "order_snippet.html" %}
      </div>

    </div>

  </div>
</main>

{% endblock content %}

{% block extra_scripts %}
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var hideable_shipping_form = $('.hideable_shipping_form');
    var hideable_billing_form = $('.hideable_billing_form');

    var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
    var use_default_billing = document.querySelector("input[name=use_default_billing]");

    if (use_default_shipping) {
      use_default_shipping.addEventListener('change', function () {
        if (this.checked) {
          hideable_shipping_form.hide();
        } else {
          hideable_shipping_form.show();
        }
      });
    }

    if (use_default_billing) {
      use_default_billing.addEventListener('change', function () {
        if (this.checked) {
          hideable_billing_form.hide();
        } else {
          hideable_billing_form.show();
        }
      });
    }



    var placeOrderBtn = document.getElementById('place-order-btn');
    placeOrderBtn.addEventListener('click', function () {
      document.getElementById('checkout-form').submit();
    });
  });
</script>
{% endblock extra_scripts %}

templates/contactus.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>NR-Contact</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<style>
    body {
        background-color: rgb(251, 218, 179);
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    .container {
        text-align: center;
        max-width: 600px;
        margin: 0 auto;
    }

    .heading {
        text-align: center;
        padding: 12rem 3rem;
        margin-top: 5%;
    }

    .heading span {
        font-size: 3rem;
        font-weight: 700;
        background: rgb(255, 165, 0, .2);
        color: orange;
        border-radius: .5rem;
        padding: .5rem 1rem;
        text-transform: uppercase;
    }

    .heading span.space {
        background: none;
    }

    main {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-top: 20px;
    }

    fieldset {
        border: 2px solid orange;
        padding: 20px;
        border-radius: 10px;
        width: 100%;
        box-sizing: border-box;
    }

    legend {
        font-size: 20px;
        font-weight: bold;
        margin-bottom: 20px;
        color: darkorange;
    }

    label {
        display: block;
        margin-bottom: 10px;
        color: #fbbf0a;
    }

    input[type="text"],
    input[type="email"],
    input[type="number"],
    textarea {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    input[type="submit"] {
        background-color: #4CAF50;
        font-size: 20px;
        font-weight: bold;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    input[type="submit"]:hover {
        background-color: #fbbf0a;
    }

    .image img {
        width: 150px;
        height: auto;
    }

    .social-icons {
        margin: 20px 0;
    }

    .social-icons a {
        margin: 0 10px;
        text-decoration: none;
        color: rgb(252, 17, 17);
        font-size: 2rem;
        transition: color 0.1s ease-in-out;
    }

    .social-icons a:hover {
        color: #1ee5f3;
    }
</style>
{% endblock extra_head %}

{% block content %}
<main>
    <div class="image">
        <img src="{% static 'images/Logo.png' %}" alt="logo">
    </div>
    <div class="social-icons">
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-linkedin-in"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-whatsapp"></i></a>
    </div>
    <section class="container">
        <h1 class="heading">
            <span>c</span>
            <span>o</span>
            <span>n</span>
            <span>t</span>
            <span>a</span>
            <span>c</span>
            <span>t</span>
            <span class="space"></span>
            <span>u</span>
            <span>s</span>
        </h1>
        <fieldset>
            <legend>Query Form</legend>
            <form action="contactus.html" method="post">
                <label for="name">Name:</label>
                <input type="text" name="name" placeholder="Enter your name" required>
                <label for="email">Email:</label>
                <input type="email" name="email" placeholder="Enter your email" required>
                <label for="number">Mobile Number:</label>
                <input type="number" name="number" placeholder="registered mobile number">
                <label for="message">Message:</label>
                <textarea name="message" rows="4" cols="30" placeholder="Enter your message"></textarea>
                <input type="submit" value="Submit">
            </form>
        </fieldset>
    </section>
</main>
{% endblock content %}

{% block extra_body %}
<!--<footer>
    <p>&copy; 2024 NR Techcreatz Pvt Ltd. All rights reserved.</p>
</footer>-->
{% endblock extra_body %}

templates/footer.html
<footer>
  <p>&copy; 2024 NR Techcreatz Pvt Ltd. All rights reserved.</p>
</footer>

<style>
  footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px 0;
    width: 100%;
  }
</style>

<!-- <hr class=" my-4">

  <! Social icons -->
<!-- <div class="pb-4">
    <a href="#" target="_blank">
      <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="#" target="_blank">
      <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="#" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="#" target="_blank">
      <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="#" target="_blank">
      <i class="fab fa-dribbble mr-3"></i>
    </a>

    <a href="#" target="_blank">
      <i class="fab fa-pinterest mr-3"></i>
    </a>

    <a href="#" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="#" target="_blank">
      <i class="fab fa-codepen mr-3"></i>
    </a>
  </div> -->
<!-- Social icons -->

<!--Copyright-->
<!-- <div class="footer-copyright py-3" style="position: static; width: 100%;"> -->

templates/navbar.html
{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NR</title>
  <style>
    * {
      font-family: 'Nunito', sans-serif;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      text-transform: none;
      outline: none;
      border: none;
      text-decoration: none;
      transition: all .2s linear;
    }

    header {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      background: #333;
      z-index: 1000;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0.7rem 3%;
      box-shadow: 0px 1px 4px rgb(59, 59, 59);
    }

    .logo {
      font-size: 2rem;
      font-weight: bolder;
      color: #fff;
      text-transform: uppercase;
    }

    .logo span {
      color: orangered;
    }

    .navbar a {
      color: #fff;
      font-size: 1rem;
      margin: 0 .8rem;
    }

    .navbar a:hover {
      color: #f3a10a;
    }
  </style>
</head>

<body>
  <header>
    <h1 class="logo"><span>NR </span> Techcreatz<sub style="font-size: 15px;">pvt ltd</sub></h1>
    <nav class="navbar">
      <ul>
        <a href="{% url 'core:home' %}" onmouseover="this.style.color='#f3a10a'" onmouseout="this.style.color='#fff'"
          style="color: #fff;
      font-size: 1rem;
      margin: 0 .8rem; ">Home</a>
        <a href="{% url 'core:aboutus' %}" onmouseover="this.style.color='#f3a10a'" onmouseout="this.style.color='#fff'"
          style="color: #fff;
      font-size: 1rem;
      margin: 0 .8rem; ">About Us</a>
        <a href="{% url 'core:productlist' %}" onmouseover="this.style.color='#f3a10a'"
          onmouseout="this.style.color='#fff'" style="color: #fff;
  font-size: 1rem;
  margin: 0 .8rem; ">Products</a>

        <a href="{% url 'core:contactus' %}" onmouseover="this.style.color='#f3a10a'"
          onmouseout="this.style.color='#fff'" style="color: #fff;
      font-size: 1rem;
      margin: 0 .8rem; margin:10px">Contact Us</a>


        {% if request.user.is_authenticated %}

        <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
          <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
          <i class="fas fa-shopping-cart"></i>
          <span> Cart </span>
        </a>
        <a href="{% url 'core:profile' %}">
          <span class="clearfix d-none d-sm-inline-block"> Profile </span>
        </a>

        <a href="{% url 'account_logout' %}">
          <span class="clearfix d-none d-sm-inline-block"> Logout </span>
        </a>

        {% else %}

        <a href="{% url 'account_login' %}">
          <span class="clearfix d-none d-sm-inline-block"> Login </span>
        </a>

        <a href="{% url 'account_signup' %}">
          <span> Signup </span>
        </a>

        {% endif %}


      </ul>
    </nav>
  </header>
</body>

</html>





<!-- Collapse -->


<!-- Links -->
<!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> -->

<!-- Left -->
<!--<ul class="navbar-nav mr-auto">
        {% comment %} <li class="nav-item active">
          <a class="nav-link waves-effect" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
        </li> {% endcomment %}
      </ul>-->


<!-- <a href="{% url 'core:aboutus' %}" onmouseover="this.style.color='#f3a10a'" onmouseout="this.style.color='#fff'"
        style="color: #fff;
      font-size: 1rem;
      margin: 0 .8rem; ">About Us</a>
      <a href="{% url 'core:contactus' %}" onmouseover="this.style.color='#f3a10a'" onmouseout="this.style.color='#fff'"
        style="color: #fff;
      font-size: 1rem;
      margin: 0 .8rem; margin:10px">Contact Us</a>
      <a href="#" onmouseover="this.style.color='#f3a10a'" onmouseout="this.style.color='#fff'" style="color: #fff;
      font-size: 1rem;
      margin: 0 .8rem; ">Products</a> -->

<!-- Right -->
<!-- <a class="navbar-nav nav-flex-icons" style="color: #fff;font-size: 2rem; margin: 0 .8rem; ">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Login </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
          </a>
        </li> -->
{% endif %}
<!-- </a>
    </div>

  </div>
</nav> -->

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">Rs{{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-Rs{{ order.coupon.amount }}</span>
        </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total</span>
            <strong>Rs{{ order.get_total }}</strong>
        </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<main>
    <div class="container">

        <div class="table-responsive text-nowrap" style="padding-top: 5cm;">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.price }}</td>
                        <td>
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i
                                    class="fas fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i
                                    class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                            Rs{{ order_item.get_total_discount_item_price }}
                            <span class="badge badge-primary">Saving Rs{{ order_item.get_amount_saved }}</span>
                            {% else %}
                            Rs{{ order_item.get_total_item_price }}
                            {% endif %}
                            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-primary float-right' href='/productlist/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.coupon %}
                    <tr>
                        <td colspan="4"><b>Coupon</b></td>
                        <td><b>-Rs{{ object.coupon.amount }}</b></td>
                    </tr>
                    {% endif %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Order Total</b></td>
                        <td><b>Rs{{ object.get_total }}</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
                            <a class='btn btn-primary float-right' href='/productlist/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>

    </div>
</main>

{% endblock content %}

templates/orders.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}

<head style="padding-top: 15cm ;">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Orders</title>
</head>

<body style="padding: 5cm 0cm 0cm 5cm;">
    <h1>Your Orders</h1>
    {% if orders %}
    <ul>
        {% for order in orders %}
        <li>
            <h2>Order ID: {{ order.id }}</h2>
            <p>Ordered Date: {{ order.ordered_date }}</p>
            <p>Status:
                {% if order.being_delivered %}
                Being Delivered
                {% elif order.received %}
                Received
                {% elif order.refund_requested %}
                Refund Requested
                {% elif order.refund_granted %}
                Refund Granted
                {% else %}
                Processing
                {% endif %}
            </p>
            <h3>Items:</h3>
            <ul>
                {% for order_item in order.items.all %}
                <li>
                    <h4>{{ order_item.item.title }}</h4>
                    <p>Price: {{ order_item.item.price }}</p>
                    <!-- <p>Discount Price: {{ order_item.item.discount_price }}</p> -->
                    <img src="{{ order_item.item.image.url }}" alt="{{ order_item.item.title }}"
                        style="width:100px;height:100px;">
                    <p>Quantity: {{ order_item.quantity }}</p>
                </li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>You have no orders.</p>
    {% endif %}
</body>
{% endblock extra_head %}

templates/payment_cod.html
{% extends "base.html" %}
{% block content %}
<main>
    <div class="container wow fadeIn">

        <h2 class="my-5 h2 text-center">Cash on Delivery</h2>

        <div class="row">

            <div class="col-md-12 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="mb-3">Order Summary</h4>
                        {% include "order_snippet.html" %}
                        <form action="." method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Confirm Order</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
</main>
{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<main>
  <div class="container" style="padding-top: 5cm;">

    <h2>Request Refund</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

  </div>
</main>

{% endblock content %}

templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>